### ISSUE TITLE
avoid listing public datasets

### ISSUE THREAD

**Issue by ChristopherBarrington** [higlass/higlass-manage#15] opened 2018-10-29 15:34 UTC
I am trying to set up a server but do not want to include all of the cools (etc) from the higlass public server. To start the local server I ran `higlass-manage start --no-public-data` but the (long) list of public data are still listed.

`cat /usr/local/bin/higlass-manage` tells me I have `0.2.2` installed.

**Comment by pkerpedjiev** [comment] 2018-10-29 15:57
Sorry, I'm having trouble reproducing this. 

Could you try running the following and seeing if the issue persists?

```
higlass-manage stop
higlass-manage start --no-public-data
higlass-manage browse
```

**Comment by ChristopherBarrington** [comment] 2018-10-29 16:03
When I run the commands, I get nothing unexpected (I think)

```
[babs@FJPC302 higlass]$ higlass-manage stop
Instance not running: default
[babs@FJPC302 higlass]$ higlass-manage start --no-public-data
Pulling latest image... doneData directory: /home/babs/hg-data
Temp directory: /tmp/higlass-docker
Starting... default 8989
Docker started: higlass-manage-container-default
Waiting to start (tilesets)...
Waiting to start (tilesets)...
Waiting to start (tilesets)...
Non 200 status code (req.status_code), waiting...
Started
[babs@FJPC302 higlass]$ higlass-manage browse
[babs@FJPC302 higlass]$
```

![image](https://user-images.githubusercontent.com/7288036/47663129-3378d600-db94-11e8-8808-5619a81c6a59.png)

**Comment by pkerpedjiev** [comment] 2018-10-29 16:21
OK, I'm not sure why it's still showing those datasets.

To turn them off, you can do the following:

1. Create a super-user account: `higlass-manage createsuperuser`
2. Log into the admin interface: http://localhost:8989/admin
3. Open up the View confs
4. Open up the viewconf with a uuid of `default`
5. Where it says `trackSourceServers`, remove the `http://higlass.io/api/v1` entry.
6. Open up the app (localhost:8989/app) and proceed as normal.

Just out of curiosity, in the list of `viewconfs`, do you see one called `default_local`?

**Comment by ChristopherBarrington** [comment] 2018-10-29 16:34
OK. So that is how I get the superuser login. I was confused with that. Yes that now removes the public datasets.

There is a `default_local` profile that is pretty bare:

`{"count": 0, "next": null, "previous": null, "results": [], "trackSourceServers": ["/api/v1"]}`

I am still at a loss as to why the `--no-public-data` isn't working for me. Is there a way that to start the server with a custom conf file?

**Comment by pkerpedjiev** [comment] 2018-10-29 16:52
There isn't a way to start it with a custom conf file.

If you wanted to investigate, you could clone the repo and throw some print statements here: https://github.com/higlass/higlass-manage/blob/88499397eefa7b1c2034aedc93a8db96043a6d0e/higlass_manage.py#L571

It's obviously creating the barebones viewconf (`default_local`) but then I presume it's not copying it over to the the website. Not sure why.

You could also open the network console in Chrome and look at the source of `localhost:8989/app` to see if it's actually requesting `default_local`. Although I doubt that it is because modifying `default` fixed the problem for you.

**Comment by ChristopherBarrington** [comment] 2018-10-29 17:13
The expected behaviour of the `--no-public-data` is the equivalent of removing the URL from the trackSourceServers array though - is that what should normally happen?

But on my installation that is not working correctly? I'm very confused. So if I edit the script to add in some print statements how do I then run it without overwriting the already installed version? I installed it using `pip3 install higlass-manage`.

**Comment by pkerpedjiev** [comment] 2018-10-29 18:05
OK, so a bit of background. When you go to localhost:8989/app, that loads a page which requests a viewconf and uses it to initialize the higlass display. By default, it looks for a viewconf with the id `default`. 

What `--no-public-data` does is create a barebones viewconf with only one track source server - the one running locally (`/api/v1`). It then uploads that viewconf to the local server and gives it the id `default_local`: https://github.com/higlass/higlass-manage/blob/88499397eefa7b1c2034aedc93a8db96043a6d0e/higlass_manage.py#L571

After that, the website at localhost:8989/app needs to be directed to look for the `default_local` viewconf. That's done by a simple search and replace here: https://github.com/higlass/higlass-manage/blob/88499397eefa7b1c2034aedc93a8db96043a6d0e/higlass_manage.py#L573

If you'd like to try it out, I recommend creating a virtual environment. I use conda and run `conda create my_env_name python=3.6; source activate my_env_name`. Then from within the cloned repo, run `pip uninstall higlass-manage; python setup.py develop`. That way, the `higlass-manage` commands will be run from that local directory. Once you're done and want to use the version from pip, you can just run `pip install higlass-manage` again.

I hope that helps. And thanks for your patience and assistance!

**Comment by ChristopherBarrington** [comment] 2018-10-30 13:19
Thanks for the information. I will get conda installed and give that route a go. I did add some print statements and reran the setup.py script and pointing it to a new installation directory. But all of the output seemed to make sense.

I took a look inside the hg-launcher asset and it seems the sed inplace replace worked ok and the default config should be ignored... If I specify the default_local config file in the URL the webpage does not give me the higlass viewer any more.

![image](https://user-images.githubusercontent.com/7288036/47720614-33d1a980-dc46-11e8-84a4-d5a921525106.png)

Just for added confusion, I ran `higlass-manage view --no-public-data my.mcool` using a Ubuntu VM and `higlass-manage` `0.2.1` and this gave me a higlass webpage with just the data that I had previously ingested. When I run the same command in my Fedora machine which has 0.2.2 installed I get the following error: `OSError: [Errno 18] Invalid cross-device link: 'YUK902.multires.cool' -> '/tmp/higlass-docker/YUK902.multires.cool'` But even on the 0.2.1 Ubuntu version I cannot get `higlass-manage start --no-public-data` to work as expected.

**Comment by ChristopherBarrington** [comment] 2018-10-30 13:33
If I change the config that is created to add some additional parameters the --no-public-data options gives me a higlass session that works but only if I specify `/?config=default_local`

https://github.com/higlass/higlass-manage/blob/88499397eefa7b1c2034aedc93a8db96043a6d0e/higlass_manage.py#L563

to include

```
        config = {
            "editable": True,
            "views": [{
                "tracks": {
                    "top": [],
                    "center": [],
                    "left": [],
                    "right": [],
                    "bottom": []
                },
                "layout": {
                    "w": 12,
                    "h": 12,
                    "x": 0,
                    "y": 0
                }
            }],
            "trackSourceServers": ['http://localhost:{}/api/v1/'.format(port)]
        }
```
I'm sorry to keep going back to this but I really want to solve it - I would like to create multiple higlass sessions for collaborators, each of which can view a specific set of data (that I can specifically ingest without issue - so far...) and not have all published data listed. Perhaps there is a more efficient way to achieve this than using `--no-public-data`? I appreciate the help to get it sorted out.

**Comment by pkerpedjiev** [comment] 2018-10-30 13:43
No worries. I'd like to get this to work as well :)

Could you post a screenshot of the chrome developer console when you go to http://localhost:8989 and http://localhost:8989/?config=default_local?

**Comment by ChristopherBarrington** [comment] 2018-10-30 13:53
Thank you. I started by making a clean start:

```
[babs@FJPC302 higlass-manage]$ higlass-manage stop
[babs@FJPC302 higlass-manage]$ sudo rm -rf ~/hg-data/
[sudo] password for babs:
[babs@FJPC302 higlass-manage]$ higlass-manage list
[babs@FJPC302 higlass-manage]$ higlass-manage start --no-public-data
Pulling latest image... doneData directory: /home/babs/hg-data
Temp directory: /tmp/higlass-docker
Starting... default 8989
Docker started: higlass-manage-container-default
Waiting to start (tilesets)...
Waiting to start (tilesets)...
Waiting to start (tilesets)...
Non 200 status code (req.status_code), waiting...
Started
```

![image](https://user-images.githubusercontent.com/7288036/47722718-f4598c00-dc4a-11e8-915c-5a8868b7d588.png)

![image](https://user-images.githubusercontent.com/7288036/47722811-21a63a00-dc4b-11e8-897d-3a02d97c383e.png)

**Comment by pkerpedjiev** [comment] 2018-10-30 14:11
I'm going to set up a linux virtual machine to try to reproduce this. 

In the meantime, if you could post the output of the network panel of the console for 10.1.208.70:8989, that would be helpful.

Also, what do you get then you go to 10.2.208.70:8989/api/v1/viewconfs/?d=default_local

**Comment by ChristopherBarrington** [comment] 2018-10-30 14:44
![image](https://user-images.githubusercontent.com/7288036/47726108-bb70e580-dc51-11e8-80bb-6855cc0cacda.png)

![image](https://user-images.githubusercontent.com/7288036/47726070-a85e1580-dc51-11e8-9a2e-be8d40dae240.png)

(the default_local config does not give me the higlass toolbar across the top)

I had to go to localhost rather than the IP address for viewconfs. I am connecting to the Fedora machine via ssh and launching the server then opening firefox from the Fedora machine.

![image](https://user-images.githubusercontent.com/7288036/47726338-30dcb600-dc52-11e8-9824-bde6141efa51.png)

**Comment by pkerpedjiev** [comment] 2018-10-30 18:22
Thanks! I managed to reproduce the issue in a virtual machine. Should have a fix by tomorrow.

**Comment by pkerpedjiev** [comment] 2018-10-30 18:52
I pushed a fix to the master branch. Would you mind trying it before I issue a new release?

**Comment by ChristopherBarrington** [comment] 2018-10-31 09:42
Only an hour for the fix? Great! I have cloned and resinstalled and it seems to be working as expected. Perfect.

```
 git clone https://github.com/higlass/higlass-manage
 cd higlass-manage/
 PYTHONPATH='/home/babs/working/barrinc/pips//lib/python3.6/site-packages/' python3 setup.py install --prefix /home/babs/working/barrinc/pips/ --record record.txt
 higlass-manage stop
 PYTHONPATH='/home/babs/working/barrinc/pips//lib/python3.6/site-packages/' /home/babs/working/barrinc/pips/bin/higlass-manage start --no-public-data
```
I have installed it in a temporary directory as you can see (did not get around to conda on the test machine yet) but I would need to update the `pip3` installed version. If I rerun the `pip3 install` command and the new version is available online it should take care of everything for me, if I understand correctly?

**Comment by pkerpedjiev** [comment] 2018-10-31 15:35
It's been a while since I installed anything outside of conda so I'm not sure.

Only one way to find out :) I just created `v0.2.3` of `higlass-manage` so you should be able to install it using `pip3 install --U higlass-manage`.

**Comment by ChristopherBarrington** [comment] 2018-10-31 16:02
Thanks. `pip3` did the update and I see it was 0.2.3. I started the server again and got a bit of output:

```
ret: ExecResult(exit_code=1, output=b'Traceback (most recent call last):\n  File "higlass-server/manage.py", line 22, in <module>\n    execute_from_command_line(sys.argv)\n  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line\n    utility.execute()\n  File "/opt/conda/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute\n    self.fetch_command(subcommand).run_from_argv(self.argv)\n  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv\n    self.execute(*args, **cmd_options)\n  File "/opt/conda/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute\n    output = self.handle(*args, **options)\n  File "/opt/conda/lib/python3.6/site-packages/django/core/management/commands/shell.py", line 86, in handle\n    exec(options[\'command\'])\n  File "<string>", line 1, in <module>\n  File "/opt/conda/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method\n    return getattr(self.get_queryset(), name)(*args, **kwargs)\n  File "/opt/conda/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get\n    self.model._meta.object_name\ntilesets.models.DoesNotExist: ViewConf matching query does not exist.\n')
ret: b'{"uid": "default_local"}'
```

I'm not sure if that is normal? It looks like an error message? But when I go to the browser it all looks like it is working great.

**Comment by pkerpedjiev** [comment] 2018-10-31 16:15
Whoops, that's not an error. It'll be gone 0.2.4.

Thanks for all your help in getting this resolved!

**Closed by pkerpedjiev** 2018-10-31 16:15 UTC

**Comment by ChristopherBarrington** [comment] 2018-10-31 16:19
OK, thank you for sorting the problem so quickly.
